//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppInvoiceSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InvoiceHeader()
        {
            this.InvoiceDetails = new HashSet<InvoiceDetail>();
        }
    
        public long ID { get; set; }
        public string CustomerName { get; set; }
        public System.DateTime Invoicedate { get; set; }
        public Nullable<int> CashierID { get; set; }
        public int BranchID { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Cashier Cashier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetails { get; set; }
    }
}
